### ISSUE TITLE
climate-sensor-service: Convert brightness service to climate service.

### ISSUE THREAD

**Issue by Christo-JvV** [mario-r99/jarvil#46]
As an administrator, I want a sensor service that detects the climate state in the room:
AC:
- temperature, humidity, brightness sensors
- relays actuators
- should send all messages to the MQTT broker in a defined timestamp
- environmental variables: used arduino pins / usb connection

- [x] change service name
- [x] add environment variables
- [ ] add temperature reading & publishing
- [ ] add humidity reading & publishing
- [x] add relay subscribing & setting

**Comment by mario-r99** [comment]
Added in #58
